# ===============================================================
# NexT Theme 优化配置
# ===============================================================

# ---------------------------------------------------------------
# Site Information Settings
# ---------------------------------------------------------------

# 网站图标
favicon:
  small: /images/favicon-16x16-next.png
  medium: /images/favicon-32x32-next.png
  apple_touch_icon: /images/apple-touch-icon-next.png

# 头像设置
avatar:
  url: /images/avatar.gif
  rounded: true
  rotated: false

# ---------------------------------------------------------------
# Scheme Settings
# ---------------------------------------------------------------

# 选择主题风格 (Muse | Mist | Pisces | Gemini)
scheme: Mist

# ---------------------------------------------------------------
# Menu Settings
# ---------------------------------------------------------------

menu:
  home: / || fa fa-home
  about: /about/ || fa fa-user
  tags: /tags/ || fa fa-tags
  categories: /categories/ || fa fa-th
  archives: /archives/ || fa fa-archive
  #schedule: /schedule/ || fa fa-calendar
  #sitemap: /sitemap.xml || fa fa-sitemap
  #commonweal: /404/ || fa fa-heartbeat

# Enable / Disable menu icons / item badges.
menu_settings:
  icons: true
  badges: false

# ---------------------------------------------------------------
# Sidebar Settings
# ---------------------------------------------------------------

sidebar:
  position: left
  display: always
  padding: 18
  offset: 12

# 社交链接
social:
  GitHub: https://github.com/Czh0618 || fab fa-github
  E-Mail: mailto:Czh0618@example.com || fa fa-envelope
  #Weibo: https://weibo.com/yourname || fab fa-weibo
  #Twitter: https://twitter.com/yourname || fab fa-twitter
  #FB Page: https://www.facebook.com/yourname || fab fa-facebook
  #StackOverflow: https://stackoverflow.com/yourname || fab fa-stack-overflow
  #YouTube: https://youtube.com/yourname || fab fa-youtube
  #Instagram: https://instagram.com/yourname || fab fa-instagram
  #Skype: skype:yourname?call|chat || fab fa-skype

social_icons:
  enable: true
  icons_only: false
  transition: false

# 关注我
follow_me:
  #Twitter: https://twitter.com/username || fab fa-twitter
  #Telegram: https://t.me/channel_name || fab fa-telegram
  #WeChat: /images/wechat_qr.jpg || fab fa-weixin
  #RSS: /atom.xml || fa fa-rss

# ---------------------------------------------------------------
# Footer Settings
# ---------------------------------------------------------------

footer:
  since: 2022
  icon:
    name: fa fa-heart
    animated: true
    color: "#ff0000"
  copyright:
  powered: true

# ---------------------------------------------------------------
# Post Settings
# ---------------------------------------------------------------

# 自动摘要设置
excerpt_description: true
read_more_btn: true

# 文章元信息
post_meta:
  item_text: true
  created_at: true
  updated_at:
    enable: true
    another_day: true
  categories: true

# 文章编辑链接
post_edit:
  enable: false
  url: https://github.com/user-name/repo-name/tree/branch-name/subdirectory-name # Link for view source.

# 显示文章结束标记
post_end_tag:
  enable: false

# ---------------------------------------------------------------
# Custom Page Settings
# ---------------------------------------------------------------

# TagCloud settings for tags page.
tagcloud:
  min: 12 # Minimun font size in px
  max: 30 # Maxium font size in px
  amount: 200 # Total amount of tags
  orderby: name # Order of tags
  order: 1 # Sort order

# ---------------------------------------------------------------
# Misc Theme Settings
# ---------------------------------------------------------------

# 代码块设置
codeblock:
  theme:
    light: default
    dark: stackoverflow-dark
  prism:
    light: prism
    dark: prism-dark
  copy_button:
    enable: true
    show_result: false
    style: flat

# 返回顶部
back2top:
  enable: true
  sidebar: false
  scrollpercent: false

# 阅读进度
reading_progress:
  enable: false
  position: top
  color: "#37c6c0"
  height: 3px

# 书签
bookmark:
  enable: false
  color: "#222"
  save: auto

# ---------------------------------------------------------------
# Font Settings
# ---------------------------------------------------------------

font:
  enable: false

# ---------------------------------------------------------------
# Third Party Plugins & Services Settings
# ---------------------------------------------------------------

# 数学公式
math:
  mathjax:
    enable: true
    mhchem: false
  katex:
    enable: false
    copy_tex: false

# 搜索
local_search:
  enable: true
  trigger: auto
  top_n_per_article: 1
  unescape: false
  preload: false

# ---------------------------------------------------------------
# Comments Settings
# ---------------------------------------------------------------

comments:
  style: tabs
  active:
  storage: true
  lazyload: false
  nav:

# Disqus
disqus:
  enable: false
  shortname:
  count: true

# ---------------------------------------------------------------
# Statistics and Analytics Settings
# ---------------------------------------------------------------

# Google Analytics
google_analytics:
  tracking_id: # GA_TRACKING_ID
  only_pageview: false

# 百度统计
baidu_analytics: # BAIDU_ANALYTICS_ID

# 字数统计
symbols_count_time:
  separated_meta: true
  item_text_post: true
  item_text_total: false

# ---------------------------------------------------------------
# Content Sharing Services
# ---------------------------------------------------------------

# AddThis Share. See: https://www.addthis.com
add_this_id:

# ---------------------------------------------------------------
# Search Services
# ---------------------------------------------------------------

# Swiftype Search API Key
swiftype_key:

# Baidu Search API Key
baidu_search_api_key:

# Algolia Search
algolia_search:
  enable: false
  hits:
    per_page: 10

# ---------------------------------------------------------------
# Chat Services
# ---------------------------------------------------------------

# Chatra Support
chatra:
  enable: false
  async: true
  id: # visit https://chatra.io/ to get your ChatraID

# Tidio Support
tidio:
  enable: false
  key: # Public Key, get it from dashboard. See: https://www.tidio.com/

# ---------------------------------------------------------------
# Tags Settings
# ---------------------------------------------------------------

note:
  style: flat
  icons: false
  light_bg_offset: 0

tabs:
  transition:
    tabs: false
    labels: true

label: true

# ---------------------------------------------------------------
# Animation Settings
# ---------------------------------------------------------------

motion:
  enable: false
  async: false
  transition:
    post_block: fadeIn
    post_header: fadeInDown
    post_body: fadeInDown
    coll_header: fadeInLeft
    sidebar: fadeInUp

# ---------------------------------------------------------------
# SEO Settings
# ---------------------------------------------------------------

index_with_subtitle: false

exturl: false

google_site_verification:

bing_site_verification:

yandex_site_verification:

baidu_site_verification:

# ---------------------------------------------------------------
# Third Party Plugins
# ---------------------------------------------------------------

# Star rating support to each article.
# To get your ID visit https://widgetpack.com
rating:
  enable: false
  id:     # <app_id>
  color:  fc6423

# ---------------------------------------------------------------
# Live2D Settings
# ---------------------------------------------------------------

live2d:
  enable: false
  scriptFrom: local # jsdelivr CDN
  pluginRootPath: live2dw/ # Root path of plugin to be on the site (Relative)
  pluginJsPath: lib/ # JavaScript path related to plugin's root (Relative)
  pluginModelPath: assets/ # Model path related to plugin's root (Relative)
  tagMode: false # Whether only to replace live2d tag in posts
  debug: false # Whether to show debug info
  model:
    use: live2d-widget-model-wanko # Model package's name
  display:
    position: right # Side to be shown
    width: 150 # Pixel value
    height: 300 # Pixel value
  mobile:
    show: true # Whether to show on mobile
